/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ManagedDatabaseLogicalDatabase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedDatabaseMysql) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedDatabaseOpensearch) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedDatabasePostgresql) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedDatabaseRedis) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedDatabaseUser) Hub() {}
