/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ManagedObjectStorage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedObjectStoragePolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedObjectStorageUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedObjectStorageUserAccessKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ManagedObjectStorageUserPolicy) Hub() {}
