apiVersion: server.upcloud.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/server
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    hostname: terraform.example.tld
    labels:
      env: dev
      production: "false"
    login:
    - keys:
      - <YOUR SSH PUBLIC KEY>
      user: myusername
    networkInterface:
    - type: public
    plan: 1xCPU-1GB
    template:
    - backupRule:
      - interval: daily
        retention: 8
        time: "0100"
      size: 25
      storage: Ubuntu Server 20.04 LTS (Focal Fossa)
    zone: de-fra1
