apiVersion: network.upcloud.io/v1alpha1
kind: Router
metadata:
  name: example
spec:
  forProvider:
    name: crossplane-example
---
apiVersion: network.upcloud.io/v1alpha1
kind: Network
metadata:
  name: example
spec:
  forProvider:
    ipNetwork:
    - address: 10.11.0.0/24
      dhcp: true
      dhcpDefaultRoute: false
      family: IPv4
      gateway: 10.11.0.1
    name: crossplane_private_net_x
    zone: de-fra1
---
apiVersion: network.upcloud.io/v1alpha1
kind: Network
metadata:
  name: example-2
spec:
  forProvider:
    ipNetwork:
    - address: 10.12.0.0/24
      dhcp: true
      dhcpDefaultRoute: false
      family: IPv4
    name: crossplane_private_net_x_2
    zone: de-fra1
    routerRef:
      name: example