apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-upcloud
  annotations:
    meta.crossplane.io/maintainer: UpCloud
    meta.crossplane.io/source: "https://github.com/UpCloudLtd/provider-upcloud"
    meta.crossplane.io/description: "Crossplane provider to manage UpCloud services in Kubernetes"
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/readme: |
      This is an official Crossplane provider for [UpCloud](https://upcloud.com).
      Detailed instructions on how to install and use the provider can be found in the [GitHub repository](https://github.com/UpCloudLtd/provider-upcloud).
      If you have any questions or need help, please [create a new issue in GitHub](https://github.com/UpCloudLtd/provider-upcloud/issues/new).
