name: Run e2e tests

on:
  workflow_dispatch:

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Setup Go"
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'

      - name: "Setup submodules"
        run: make submodules

      - name: "Run e2e tests"
        env:
            UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
            UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}
        if: env.UPCLOUD_PASSWORD != ''
        run: make e2e
